### PR TITLE
feat(provision) add jq and httpie packages

### PR DESCRIPTION
**Pull request by hbagdi**

### CODE REVIEW

**Comment by Tieske** [comment]
since the image already takes long to build, couldn't we change the "KONG_PROFILING" variable and rename it to "KONG_UTILITIES" or something similar? Making it work in a way that it installs the basics (which already is quite a lot) and if that utilities thing is set, it would additionally build `systemtap`, `httpie`, `jq`, etc.

**Comment by hbagdi** [comment]
@Tieske sounds good. Will refactor and ping you once ready.

**Comment by Tieske** [comment]
@hbagdi Thx. Merged after adding the docs.

**Comment by hbagdi** [comment]
Oops, documentation skipped me. Apologies.
Thanks!

**Pull request merged**
